name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set Project Version
      run: |
        echo "VERSION=$(date +'%d-%m-%Y-%H-%M')" >> $GITHUB_ENV
    - name: Change POM Version
      run: |
        echo "VERSION : $VERSION"
        mvn versions:set -DnewVersion=$VERSION
    - name: Deploy Artifact
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Docker Image generation
      run: mvn spring-boot:build-image -Dgithub.sha=${{ github.sha }}
    - name: Docker Image Push
      run: |
        docker images
        docker push -a ghcr.io/${{env.GITHUB_REPOSITORY}}
