name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: pom versioning
      run: |
        echo "VERSIONING=$(date +'%d-%m-%Y-%H-%M')" >> $GITHUB_ENV
    - name: Maven Deploy
      run: ./mvnw -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Generate Docker Image
      run: ./mvnw spring-boot:build-image -Dgithub.sha=${{ github.sha }}
    - name: Docker Image push to ghcr.io
      run: |
        docker images
        docker push -a ghcr.io/${{env.GITHUB_REPOSITORY}}
